### ISSUE TITLE
Game crashes after trying to use the exit option

### ISSUE THREAD

**Issue by SofyUchiha** [kaaass/Kero-Blaster-vita#1]
First of all, thanks for your work! I love this game.
You know, when you enter the menu and try to use the exit option, to exit the game, the game crashes. It throws error C2-12828-1
Is it possible to fix it?
I have also had difficulties remapping the buttons, I want to exchange croos for circle and it won't let me. I don't know if I'm doing something wrong.
Thank you very much!

**Comment by kaaass** [comment]
Thank you for testing!

> when you enter the menu and try to use the exit option, to exit the game, the game crashes

This is an acknowledged issue. I had already found the problem and would probably fix it in the next version, released together with other bugs (if we have any).

> I have also had difficulties remapping the buttons, I want to exchange croos for circle and it won't let me.

Yes, the key config logic is a little bit confusing. Using the touch screen to enter the keyconfig menu should be easier.  Besides, F1 has been mapped to L-trigger.

**Comment by kaaass** [comment]
This bug is fixed in v1.1.
