### ISSUE TITLE
Can you add support for the latest "Pink Hour" version (1.6.1)?

### ISSUE THREAD

**Issue by Hassan2402** [kaaass/Kero-Blaster-vita#3]
Hi! How are you? I wanted to ask you if it is possible to add support for the latest version "Pink Hour", since the one that supports the port is the previous one (1.6.0)
The latest version (1.6.1) includes:
- Improved compatibility with older devices
- Controller support and redesigned settings menu

Available here: https://play.google.com/store/apps/details?id=jp.studiopixel.pinkhour
Thanks for this great port!

**Comment by kaaass** [comment]
Thanks! This is implemented in the v1.2 release.
